data:
  raw_data_path: "data/raw/server_metrics.csv"
  processed_data_path: "data/processed/processed_metrics.csv"
  features:
    - cpu_usage
    - memory_usage
    - disk_io
    - network_latency
  target: failure_cause
model:
  type: random_forest
  params:
    n_estimators: 100
    random_state: 42
anomaly_detection:
  contamination: 0.1
logging:
  log_file: "logs/app.log"
  level: INFO
