apiVersion: apps/v1
kind: Deployment
metadata:
  name: fault-prediction-service
  namespace: sre
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fault-prediction
  template:
    metadata:
      labels:
        app: fault-prediction
    spec:
      containers:
      - name: fault-prediction
        image: fault-prediction-service:latest
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: fault-prediction-service
  namespace: sre
spec:
  selector:
    app: fault-prediction
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fault-prediction-hpa
  namespace: sre
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fault-prediction-service
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
